"""Bake smooth plush silhouettes to OBJ. Optional authoring dependency: numpy.
Run from the project root; Godot imports the committed models without Python.
"""
from pathlib import Path
import numpy as np

OUT = Path(__file__).resolve().parents[1] / 'godot' / 'assets'
OUT.mkdir(parents=True, exist_ok=True)

def ellipsoid(p, center, radius):
    q = p - np.array(center)
    r = np.array(radius)
    a = np.linalg.norm(q / r, axis=-1)
    b = np.linalg.norm(q / (r * r), axis=-1)
    return a * (a - 1) / np.maximum(b, 1e-7)

def smooth_union(a, b, amount):
    h = np.maximum(amount - np.abs(a - b), 0) / amount
    return np.minimum(a, b) - h * h * amount * .25

def polygonize(grid, field):
    offsets = [(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]
    dims = np.array(field.shape) - 1
    points = np.stack([grid[x:x+dims[0],y:y+dims[1],z:z+dims[2]].reshape(-1,3) for x,y,z in offsets],axis=1)
    values = np.stack([field[x:x+dims[0],y:y+dims[1],z:z+dims[2]].reshape(-1) for x,y,z in offsets],axis=1)
    surface = (values.min(axis=1)<0) & (values.max(axis=1)>=0)
    points, values = points[surface], values[surface]
    triangles=[]
    for tet in [(0,5,1,6),(0,1,2,6),(0,2,3,6),(0,3,7,6),(0,7,4,6),(0,4,5,6)]:
        p,v = points[:,tet],values[:,tet]
        masks = (v<0).astype(int) @ np.array([1,2,4,8])
        for mask in range(1,15):
            selected=masks==mask
            if not selected.any(): continue
            pp,vv=p[selected],v[selected]
            inside=[i for i in range(4) if mask & (1<<i)]
            outside=[i for i in range(4) if not mask & (1<<i)]
            def edge(a,b):
                t=vv[:,a]/(vv[:,a]-vv[:,b])
                return pp[:,a]+(pp[:,b]-pp[:,a])*t[:,None]
            if len(inside)==1: triangles.append(np.stack([edge(inside[0],b) for b in outside],axis=1))
            elif len(inside)==3: triangles.append(np.stack([edge(outside[0],b) for b in inside],axis=1))
            else:
                a,b,c,d=[edge(i,j) for i in inside for j in outside]
                triangles.extend([np.stack([a,b,c],axis=1),np.stack([b,d,c],axis=1)])
    vertices,indices=np.unique(np.round(np.concatenate(triangles).reshape(-1,3),7),axis=0,return_inverse=True)
    return vertices,indices.reshape(-1,3)

def sculpt(name, bounds, shapes, step=.045):
    low, high = np.array(bounds[0]), np.array(bounds[1])
    axes = [np.arange(low[i], high[i] + step, step) for i in range(3)]
    grid = np.stack(np.meshgrid(*axes, indexing='ij'), axis=-1)
    field = ellipsoid(grid, *shapes[0][:2])
    for center, radius, blend in shapes[1:]:
        field = smooth_union(field, ellipsoid(grid, center, radius), blend)
    vertices, faces = polygonize(grid,field)
    # SDF grows towards the outside. Compute its smooth normals directly.
    def sample(p):
        f = ellipsoid(p, *shapes[0][:2])
        for center, radius, blend in shapes[1:]: f = smooth_union(f, ellipsoid(p, center, radius), blend)
        return f
    normals = np.stack([(sample(vertices + np.eye(3)[i] * .002) - sample(vertices - np.eye(3)[i] * .002)) for i in range(3)], axis=-1)
    normals /= np.maximum(np.linalg.norm(normals, axis=-1, keepdims=True), 1e-7)
    with (OUT / f'{name}.obj').open('w', encoding='utf-8') as f:
        f.write('# Sunny Cup sculpted plush mesh; generated by scripts/sculpt_pony.py\n')
        for p in vertices: f.write('v %.6f %.6f %.6f\n' % tuple(p))
        for n in normals: f.write('vn %.6f %.6f %.6f\n' % tuple(n))
        for tri in faces:
            points = vertices[tri]
            if np.dot(np.cross(points[1] - points[0], points[2] - points[0]), normals[tri].mean(axis=0)) < 0: tri = tri[::-1]
            # OBJ is CCW. Godot's importer converts its winding.
            f.write('f ' + ' '.join(f'{i+1}//{i+1}' for i in tri) + '\n')
    print(name, len(vertices), 'vertices', len(faces), 'triangles')

sculpt('pony_body', ((-.9,.5,-1.3),(.9,2.8,1.4)), [
    ((0,1.35,.15),(.64,.66,.97),.2),
    ((0,1.32,.68),(.60,.57,.58),.26),
    ((0,1.46,-.48),(.55,.63,.58),.30),
    ((0,1.96,-.61),(.36,.60,.38),.34),
    ((0,2.29,-.77),(.33,.31,.33),.22),
])
sculpt('pony_head', ((-.7,-.5,-1.05),(.7,.8,.6)), [
    ((0,.20,-.08),(.46,.48,.46),.2),
    ((0,-.02,-.43),(.37,.30,.40),.25),
    ((0,.04,-.18),(.43,.34,.45),.26),
], .033)
