extends RefCounted

# Snapshots synchronize a continuous clock, never individual horse positions.
# Bounded clock correction avoids the 4 Hz speed pulses of chasing snapshots.
var seconds := 0.0
var target_seconds := 0.0
var initialized := false
var cinematic: Array=JSON.parse_string(FileAccess.get_file_as_string("res://assets/cinematic.json"))

func presentation(time: float) -> Vector2:
	if time<=float(cinematic[0][0]): return Vector2(time,1)
	if time>=float(cinematic[-1][0]):
		var last: Array=cinematic[-1]
		return Vector2(float(last[1])+(time-float(last[0]))*float(last[2]),float(last[2]))
	for i in range(1,cinematic.size()):
		if time>float(cinematic[i][0]): continue
		var a: Array=cinematic[i-1]
		var b: Array=cinematic[i]
		var span:=float(b[0])-float(a[0])
		var t: float=(time-float(a[0]))/span
		var value: float=(2*t*t*t-3*t*t+1)*a[1]+(t*t*t-2*t*t+t)*span*a[2]+(-2*t*t*t+3*t*t)*b[1]+(t*t*t-t*t)*span*b[2]
		var speed: float=((6*t*t-6*t)*a[1]+(3*t*t-4*t+1)*span*a[2]+(-6*t*t+6*t)*b[1]+(3*t*t-2*t)*span*b[2])/span
		return Vector2(value,speed)
	return Vector2(time,1)

func sync(snapshot: float, reset := false) -> void:
	target_seconds=snapshot
	if reset or not initialized or absf(snapshot-seconds)>1.0:
		seconds=snapshot
		initialized=true

func advance(delta: float) -> void:
	target_seconds+=delta
	seconds+=delta*(1.0+clampf((target_seconds-seconds-delta)*2.0,-.05,.05))

# The race plan comes from React (src/raceModel.ts): each horse's distance
# behind a virtual pace-setter, as Hermite knots over the winner's progress.
# Evaluated exactly as there. Past the line every horse keeps galloping at the
# steady pace, so the run-out never brakes.
static func plan_progress(plan: Dictionary, index: int, time: float) -> float:
	var t:=maxf(time,0.0)
	var ease:=float(plan.ease)
	var stage:=float(plan.cruise)*(t-ease*(1.0-exp(-t/ease)))
	var knots: Array=plan.knots
	return stage-(deficit(knots[index],stage)-deficit(knots[int(plan.winner)],stage))

static func deficit(knots: Array, stage: float) -> float:
	var last:=knots.size()-3
	if stage<=float(knots[0]): return float(knots[1])
	if stage>=float(knots[last]): return float(knots[last+1])
	var k:=3
	while float(knots[k])<stage: k+=3
	var x0:=float(knots[k-3])
	var h:=float(knots[k])-x0
	var t:=(stage-x0)/h
	return (2*t*t*t-3*t*t+1)*float(knots[k-2])+(t*t*t-2*t*t+t)*h*float(knots[k-1])+(-2*t*t*t+3*t*t)*float(knots[k+1])+(t*t*t-t*t)*h*float(knots[k+2])

# A fixed race for native previews and tests, generated by the same TypeScript.
static func preview_plan() -> Dictionary:
	return JSON.parse_string(FileAccess.get_file_as_string("res://assets/race_preview.json"))
